### ISSUE TITLE
Support for multiline logs

### ISSUE THREAD

**Issue by anderiv** [python-beaver/python-beaver#108]
Before I start work on implementing this myself, I just wanted to verify:

Does beaver currently support the shipping of multiline logs? Python stack traces, etc.?

If not, I'll start working on implementing this functionality.

Thanks!

**Comment by raghusumanth** [comment]
Hi Josegonzalez,
 
           Will Beaver 36.2.1 support for parsing a multiline log file into single line?

**Comment by josegonzalez** [comment]
Yes, beaver has for a while. See the docs on the multi-ine regex.
