### ISSUE TITLE
add_field adds values as array, why?

### ISSUE THREAD

**Issue by timstoop** [python-beaver/python-beaver#252]
Hi,

I noticed that add_field adds the values as an array, is there a specific reason for that? I fail to see the logic behind it, since you cannot actually add multiple values to the field. And even if you could, wouldn't it make more sense to specifically tell it that you want an array? Something like:

add_field: my_array,[value1,value2]

Maybe I'm overlooking an obvious reason for this, please enlighten me!

**Comment by morganchristiansson** [comment]
+1 - 2 years after issue reported

What's the purpose of unnessecarily wrapping the values in single-element arrays? Also add_field is barely documented but this beahviour is hinted at in the docs here: http://python-beaver.readthedocs.org/en/latest/user/usage.html#environment-import-support

add_field is seemingly broken for my purposes and I'd have to use add_field_env.

Relevant code is here: https://github.com/python-beaver/python-beaver/blob/master/beaver/config.py#L413

**Comment by morganchristiansson** [comment]
Also reported as #232

**Comment by josegonzalez** [comment]
@morganchristiansson I mean, the project is open source. If you'd like to "fix" the issue for your use case, feel free to create a pull request for it.

**Comment by akhfa** [comment]
@eandriol Maybe you can make pull request so the change can be applied. I see same problem with current commit and can be solved with your fix

**Comment by josegonzalez** [comment]
If you want to add a single field, use add_field_env.

**Comment by morganchristiansson** [comment]
filebeat does this very elegantly in the 5.0 alpha release https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#configuration-fields

It's also an officially supported Elasticsearch project.

**Comment by akhfa** [comment]
@morganchristiansson no before filebeat support rabbitmq output. Logstash needs too much memory....

**Comment by josegonzalez** [comment]
If anyone would like to support work on python-beaver with a monetary contribution, I can actually work on bugs/issues such as these. Otherwise, the available workarounds will be the best you get, as at the end of the day my rent isn't paid in git commits.

Thanks for understanding.
