### ISSUE TITLE
Add an option to run a scheduled script and ship the output to logstash

### ISSUE THREAD

**Issue by tomkregenbild** [python-beaver/python-beaver#272]
A nice option the Splunk shipper has is the ability to schedule a periodic scripts to run and send the STDOUT to the index server (in out case logstash).

In many cases, this eliminates the need to use temporary log files and send the data from many small scripts into logstash.

**Comment by AltJ** [comment]
adding link to open issue mentioned above...
https://github.com/josegonzalez/python-beaver/issues/7
