### ISSUE TITLE
Need to integrate Beaver-HAPROXY-Redis

### ISSUE THREAD

**Issue by ersushantsood** [python-beaver/python-beaver#380]
Hi I am trying to integrate Beaver with Haproxy and Haproxy in turn would forward requests to Redis sentinel . Can you please let me know the bever configs i need to set for this integration and how i would be able to send redis key via haproxy to redis server.

**Comment by josegonzalez** [comment]
You need to set your haproxy lb to be a TCP load balancer for redis. Then just configure beaver to send data to whatever port/ip you have set for haproxy. All other configuration should be the same, nothing special.

**Comment by JamieCressey** [comment]
@ersushantsood as a side note, you may be interested in the progress of #374

**Comment by ersushantsood** [comment]
Thanks for the quickest response .when I am using haproxy which transport should I mention in beaver conf.Will it work if I mention only tcp host and port of haproxy?

**Comment by ersushantsood** [comment]
Also how would I send the redis namespace to redis via haproxy

**Comment by josegonzalez** [comment]
Redis isn't an http service, it communicates over TCP. The haproxy portion is transparent, you just configure the remote host/port to be that of haproxy and the TCP protocol handles the rest like normal.

**Comment by ersushantsood** [comment]
Okie thanks for the info .will try the configs and get back in case of any issues.

**Comment by ersushantsood** [comment]
@josegonzalez  I tried using tcp host and tcp port , now logs are forwarded to haproxy IP but redis key is not getting created in Redis:
[beaver]
      2 logstash_version: 1
      7 tcp_host: xx.xxx.xx.xx
      8 tcp_port: xxxx
      9 redis_namespace: beaver
     10 
     11 [/var/log/logs.log]
     12 tags: [log1,log2]
     13 type: logs
     14 add_field_env:hostname,HOSTNAME

**Comment by JamieCressey** [comment]
@ersushantsood please can you provide your HAProxy config too? ( Code tags are your friend :) )

Does your HAProxy/Redis setup work when GET/SET'ing directly (e.g. not using Beaver)?
