### ISSUE TITLE
i am unable to do pip install beaver on windows

### ISSUE THREAD

**Issue by ersushantsood** [python-beaver/python-beaver#383]
I am getting an error while invoking pip install beaver on windows 7 machine then i am getting below error 

(venv) C:\Python34\Scripts\venv\Scripts>pip install beaver
Collecting beaver
  Using cached Beaver-36.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "\AppData\Local\Temp\pip-build-erro3cgx\beaver\setup.
py", line 51, in <module>
        pd = filter(lambda r: r.startswith('python-daemon'), requirements)[0]
    TypeError: 'filter' object is not subscriptable
 
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in Local\Temp\pip-build-erro3cgx\beaver

**Comment by ersushantsood** [comment]
Is currently Beaver supporting Windows Platform Out of the Box?

**Comment by ersushantsood** [comment]
I am getting many errors when i am trying to make it run on Windows . Above issue is resolved by commenting the if condition to remove python-daemon in setup.py . Now when i am trying to run beaver process in Windows , I am getting below error : WARNING:py.warnings:C:\Python27\lib\site-packages\beaver\config.py:282: Deprecat
ionWarning: ENV Variable support will be removed by version 20. Stop using: BEAV
ER_PATH
  warnings.warn('ENV Variable support will be removed by version 20. Stop using:
 {0}'.format(', '.join(deprecated_env_var_usage)), DeprecationWarning)

[2016-01-08 16:26:02,523] DEBUG   Logger level is DEBUG
Traceback (most recent call last):
  File "beaver", line 25, in <module>
    tail_run(args)
  File "C:\Python27\lib\site-packages\beaver\dispatcher\tail.py", line 66, in ru
n
    signal.signal(signal.SIGQUIT, cleanup)
AttributeError: 'module' object has no attribute 'SIGQUIT'

**Comment by ersushantsood** [comment]
Can you please respond on the issue.as my implementation is getting impacted

**Comment by JamieCressey** [comment]
There's an open issue (#284) and PR (#293) for Windows support which you can track.
