### ISSUE TITLE
Beaver does not reconnect if RabbitMQ server is rebooted

### ISSUE THREAD

**Issue by eyj** [python-beaver/python-beaver#385]
Probably related to #346, #281, and especially #323 

As a result of using pika.SelectConnection, both the Tornado IOLoop (a.k.a. async) and python threading are used in rabbitmq_transport.py. This leads to the unfortunate situation that if the rabbitmq server is unavailable for more than one second, beaver just stops delivering messages and never reconnects.

To reproduce: Connect beaver to rabbitmq. Stop rabbitmq. Start rabbitmq.

**Comment by JamieCressey** [comment]
Thanks for the bug reports @eyj . I've never used RabbitMQ, it was more of a community feature which developed over time. @josegonzalez may have a better understand of the background on it.

Do you have the time to create a failing test cases and fixes for this, and #386 in a couple of PRs?

**Comment by eyj** [comment]
I just put in a PR with the fixes for the two issues; unfortunately, I don't think I'll be able to set up a combined threading + async test case for this, since the actual error depends on the behaviour of the actual implementations. However, i've tested the code as it stands in production; and if more issues crop up i'll update the PR (or make new ones).
