### ISSUE TITLE
Does beaver respect dns TTLs?

### ISSUE THREAD

**Issue by geekpete** [python-beaver/python-beaver#397]
If a dns record changes, will beaver re-resolve the record after TTL expires?

This is in regard to the remote location beaver is shipping logs to, if that dns changes then will a restart of beaver be required on all hosts running the shipper?

**Comment by josegonzalez** [comment]
Depends on the underlying libraries. I think if anything uses curl, [it won't](https://github.com/curl/curl/pull/403). You'll want to check with the upstream library in use for your particular transport.

**Comment by geekpete** [comment]
Thanks.

**Comment by josegonzalez** [comment]
Note: how I get around this in production is to use an intermediate proxy on the local instance that can resolve dns and respect ttls. A good example is haproxy for redis, or having a local rabbitmq instance that federates data to your global cluster.

**Comment by geekpete** [comment]
ah ok thanks. And I think it's the pika library used with the rabbitmq transport that I use.

**Comment by jmcollin78** [comment]
In complement of this question, is the DNS resolution re-done at each new connection (or does Beaver cache the resolution until the next restart) ?

**Comment by josegonzalez** [comment]
Again, depends upon the underlying libraries. So long as the connection is completely torn down, many will retry dns resolution when starting a new connection, but I can't make that guarantee for a given transport/use-case.
