### ISSUE TITLE
mosquitto no longer exists

### ISSUE THREAD

**Issue by jeffb-stell** [python-beaver/python-beaver#398]
$ cat requirements/base.txt
boto>=2.18.0
conf_d>=0.0.4
glob2==0.3
kafka-python==0.9.5
mosquitto>=1.1
msgpack-pure>=0.1.3
pika>=0.9.14
python-daemon>=1.5.2,<=1.6.1
redis>=2.7.5
requests
$ pip install beaver
Collecting mosquitto>=1.1 (from beaver)
  Could not find a version that satisfies the requirement mosquitto>=1.1 (from beaver) (from versions: )
No matching distribution found for mosquitto>=1.1 (from beaver)

https://pypi.python.org/pypi/mosquitto 404s now.

**Comment by josegonzalez** [comment]
Sad. Mind making a pr to change that to [paho-mqtt](http://mosquitto.org/documentation/python/)?

**Comment by jeffb-stell** [comment]
Not to be a typical do-nothing issue reporter, I simply don't have the MQTT skills required to do the conversion and have any faith that it works. Sorry.

**Comment by jvheerde-sentia** [comment]
This was giving us trouble, so I've created a PR #399 .
