### ISSUE TITLE
Please create new release for current master

### ISSUE THREAD

**Issue by jvheerde-sentia** [python-beaver/python-beaver#400]
I apologize if this is not the right way to ask, I'm not sure how this is supposed to work. Would it be possible to create a new release and push it to Pypi? The current packages cannot be installed.

**Comment by beregond** [comment]
http://stackoverflow.com/questions/36568863/unable-to-install-beaver-cause-mosquitto-is-not-found-debian-jessie

**Comment by jvheerde-sentia** [comment]
See #398 and #399 , this been fixed on master.

**Comment by lmorfitt** [comment]
Hello,

I've tested the latest master on our platform (we are not using MQTT) and all seems to be functioning as expecting.

+1 for a new release.

thanks
Luke

**Comment by nullck** [comment]
Guys, please help us:

https://github.com/poise/poise-python/issues/48

**Comment by lmorfitt** [comment]
I've created a new release on github.

https://github.com/python-beaver/python-beaver/releases/tag/36.1.1

We require @josegonzalez to create a new Pypi pacakge.

thanks
Luke

**Comment by josegonzalez** [comment]
Please don't create releases via tags.

**Comment by josegonzalez** [comment]
I released 36.2.0 and deleted that tag.

**Comment by lmorfitt** [comment]
Understood. 

Thank you very much!
