### ISSUE TITLE
Please create a new release, the chef-cookbook poise-python must needs this

### ISSUE THREAD

**Issue by nullck** [python-beaver/python-beaver#401]
Hello, 

I'm a user of chef cookbook poise-python and when I ran my recipe I got this error:

Requirement already satisfied (use --upgrade to upgrade): boto>=2.8.0 in /usr/local/lib/python2.7/dist-packages (from beaver==31)
Requirement already satisfied (use --upgrade to upgrade): conf-d>=0.0.4 in /usr/local/lib/python2.7/dist-packages (from beaver==31)
Requirement already satisfied (use --upgrade to upgrade): glob2==0.3 in /usr/local/lib/python2.7/dist-packages (from beaver==31)
Collecting mosquitto>=1.1 (from beaver==31)
STDERR: /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement mosquitto>=1.1 (from beaver==31) (from versions: )
No matching distribution found for mosquitto>=1.1 (from beaver==31)
---- End output of ["/usr/bin/python2.7", "-m", "pip.__main__", "install", "beaver==31"] ----
Ran ["/usr/bin/python2.7", "-m", "pip.__main__", "install", "beaver==31"] returned 1

If you create a new release with your fix in master branch I can change in the python-poise cookbook to get this version  similar to pip.

**Comment by lmorfitt** [comment]
I've created a new release on github.

https://github.com/python-beaver/python-beaver/releases/tag/36.1.1

We require @josegonzalez to create a new Pypi pacakge.

thanks
Luke
