### ISSUE TITLE
beaver not running under AIX V7.1

### ISSUE THREAD

**Issue by alaettin66** [python-beaver/python-beaver#423]
Hello, 

i have tried to use latest beaver release on AIX V.7.1 with python V.2.7.5-4.
After installation with setup.py  and strat with beaver -c /etc/beaver.conf i am getting these 
errors:

bash-4.3# /opt/freeware/bin/beaver --confd-path /opt/freeware/etc/beaver/conf.d -c /opt/freeware/etc/beaver/conf.d/beaver.conf 
Traceback (most recent call last):
  File "/opt/freeware/bin/beaver", line 3, in <module>
    from beaver.dispatcher.tail import run as tail_run
  File "/opt/freeware/lib/python2.7/site-packages/beaver/dispatcher/tail.py", line 8, in <module>
    from beaver.config import BeaverConfig
  File "/opt/freeware/lib/python2.7/site-packages/beaver/config.py", line 8, in <module>
    from conf_d import Configuration
ImportError: No module named conf_d

could you please check where the issue is ??!! .. for others using beaver on AIX, it seams to be working !!

greets
alaettin

**Comment by alaettin66** [comment]
here is the output of the installation !!

bash-4.3# python setup.py install
/opt/freeware/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/opt/freeware/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/opt/freeware/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/beaver
copying beaver/__init__.py -> build/lib/beaver
copying beaver/base_log.py -> build/lib/beaver
copying beaver/config.py -> build/lib/beaver
copying beaver/glob_safe_config_parser.py -> build/lib/beaver
copying beaver/pidfile.py -> build/lib/beaver
copying beaver/run_queue.py -> build/lib/beaver
copying beaver/ssh_tunnel.py -> build/lib/beaver
copying beaver/unicode_dammit.py -> build/lib/beaver
copying beaver/utils.py -> build/lib/beaver
creating build/lib/beaver/dispatcher
copying beaver/dispatcher/__init__.py -> build/lib/beaver/dispatcher
copying beaver/dispatcher/tail.py -> build/lib/beaver/dispatcher
creating build/lib/beaver/tests
copying beaver/tests/__init__.py -> build/lib/beaver/tests
copying beaver/tests/fixtures.py -> build/lib/beaver/tests
copying beaver/tests/service.py -> build/lib/beaver/tests
copying beaver/tests/test_glob_sections.py -> build/lib/beaver/tests
copying beaver/tests/test_kafka_transport.py -> build/lib/beaver/tests
copying beaver/tests/test_kinesis_transport.py -> build/lib/beaver/tests
copying beaver/tests/test_sqs_transport.py -> build/lib/beaver/tests
copying beaver/tests/test_transport_config.py -> build/lib/beaver/tests
copying beaver/tests/test_zmq_transport.py -> build/lib/beaver/tests
creating build/lib/beaver/transports
copying beaver/transports/__init__.py -> build/lib/beaver/transports
copying beaver/transports/base_transport.py -> build/lib/beaver/transports
copying beaver/transports/exception.py -> build/lib/beaver/transports
copying beaver/transports/http_transport.py -> build/lib/beaver/transports
copying beaver/transports/kafka_transport.py -> build/lib/beaver/transports
copying beaver/transports/kinesis_transport.py -> build/lib/beaver/transports
copying beaver/transports/mqtt_transport.py -> build/lib/beaver/transports
copying beaver/transports/rabbitmq_transport.py -> build/lib/beaver/transports
copying beaver/transports/redis_transport.py -> build/lib/beaver/transports
copying beaver/transports/sns_transport.py -> build/lib/beaver/transports
copying beaver/transports/sqs_transport.py -> build/lib/beaver/transports
copying beaver/transports/stdout_transport.py -> build/lib/beaver/transports
copying beaver/transports/stomp_transport.py -> build/lib/beaver/transports
copying beaver/transports/tcp_transport.py -> build/lib/beaver/transports
copying beaver/transports/udp_transport.py -> build/lib/beaver/transports
copying beaver/transports/zmq_transport.py -> build/lib/beaver/transports
creating build/lib/beaver/worker
copying beaver/worker/__init__.py -> build/lib/beaver/worker
copying beaver/worker/tail.py -> build/lib/beaver/worker
copying beaver/worker/tail_manager.py -> build/lib/beaver/worker
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/beaver -> build/scripts-2.7
changing mode of build/scripts-2.7/beaver from 644 to 755
running install_lib
creating /opt/freeware/lib/python2.7/site-packages/beaver
copying build/lib/beaver/__init__.py -> /opt/freeware/lib/python2.7/site-packages/beaver
copying build/lib/beaver/base_log.py -> /opt/freeware/lib/python2.7/site-packages/beaver
copying build/lib/beaver/config.py -> /opt/freeware/lib/python2.7/site-packages/beaver
creating /opt/freeware/lib/python2.7/site-packages/beaver/dispatcher
copying build/lib/beaver/dispatcher/__init__.py -> /opt/freeware/lib/python2.7/site-packages/beaver/dispatcher
copying build/lib/beaver/dispatcher/tail.py -> /opt/freeware/lib/python2.7/site-packages/beaver/dispatcher
copying build/lib/beaver/glob_safe_config_parser.py -> /opt/freeware/lib/python2.7/site-packages/beaver
copying build/lib/beaver/pidfile.py -> /opt/freeware/lib/python2.7/site-packages/beaver
copying build/lib/beaver/run_queue.py -> /opt/freeware/lib/python2.7/site-packages/beaver
copying build/lib/beaver/ssh_tunnel.py -> /opt/freeware/lib/python2.7/site-packages/beaver
creating /opt/freeware/lib/python2.7/site-packages/beaver/tests
copying build/lib/beaver/tests/__init__.py -> /opt/freeware/lib/python2.7/site-packages/beaver/tests
copying build/lib/beaver/tests/fixtures.py -> /opt/freeware/lib/python2.7/site-packages/beaver/tests
copying build/lib/beaver/tests/service.py -> /opt/freeware/lib/python2.7/site-packages/beaver/tests
copying build/lib/beaver/tests/test_glob_sections.py -> /opt/freeware/lib/python2.7/site-packages/beaver/tests
copying build/lib/beaver/tests/test_kafka_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/tests
copying build/lib/beaver/tests/test_kinesis_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/tests
copying build/lib/beaver/tests/test_sqs_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/tests
copying build/lib/beaver/tests/test_transport_config.py -> /opt/freeware/lib/python2.7/site-packages/beaver/tests
copying build/lib/beaver/tests/test_zmq_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/tests
creating /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/__init__.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/base_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/exception.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/http_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/kafka_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/kinesis_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/mqtt_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/rabbitmq_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/redis_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/sns_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/sqs_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/stdout_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/stomp_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/tcp_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/udp_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/transports/zmq_transport.py -> /opt/freeware/lib/python2.7/site-packages/beaver/transports
copying build/lib/beaver/unicode_dammit.py -> /opt/freeware/lib/python2.7/site-packages/beaver
copying build/lib/beaver/utils.py -> /opt/freeware/lib/python2.7/site-packages/beaver
creating /opt/freeware/lib/python2.7/site-packages/beaver/worker
copying build/lib/beaver/worker/__init__.py -> /opt/freeware/lib/python2.7/site-packages/beaver/worker
copying build/lib/beaver/worker/tail.py -> /opt/freeware/lib/python2.7/site-packages/beaver/worker
copying build/lib/beaver/worker/tail_manager.py -> /opt/freeware/lib/python2.7/site-packages/beaver/worker
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/__init__.py to __init__.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/base_log.py to base_log.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/config.py to config.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/dispatcher/__init__.py to __init__.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/dispatcher/tail.py to tail.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/glob_safe_config_parser.py to glob_safe_config_parser.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/pidfile.py to pidfile.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/run_queue.py to run_queue.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/ssh_tunnel.py to ssh_tunnel.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/tests/__init__.py to __init__.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/tests/fixtures.py to fixtures.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/tests/service.py to service.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/tests/test_glob_sections.py to test_glob_sections.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/tests/test_kafka_transport.py to test_kafka_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/tests/test_kinesis_transport.py to test_kinesis_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/tests/test_sqs_transport.py to test_sqs_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/tests/test_transport_config.py to test_transport_config.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/tests/test_zmq_transport.py to test_zmq_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/__init__.py to __init__.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/base_transport.py to base_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/exception.py to exception.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/http_transport.py to http_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/kafka_transport.py to kafka_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/kinesis_transport.py to kinesis_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/mqtt_transport.py to mqtt_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/rabbitmq_transport.py to rabbitmq_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/redis_transport.py to redis_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/sns_transport.py to sns_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/sqs_transport.py to sqs_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/stdout_transport.py to stdout_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/stomp_transport.py to stomp_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/tcp_transport.py to tcp_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/udp_transport.py to udp_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/transports/zmq_transport.py to zmq_transport.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/unicode_dammit.py to unicode_dammit.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/utils.py to utils.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/worker/__init__.py to __init__.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/worker/tail.py to tail.pyc
byte-compiling /opt/freeware/lib/python2.7/site-packages/beaver/worker/tail_manager.py to tail_manager.pyc
running install_scripts
copying build/scripts-2.7/beaver -> /opt/freeware/bin
changing mode of /opt/freeware/bin/beaver to 755
running install_egg_info
Writing /opt/freeware/lib/python2.7/site-packages/Beaver-36.2.1-py2.7.egg-info

**Comment by josegonzalez** [comment]
We recommend using pip to install it, not just downloading the zip package and calling `setup.py`. Doing so means you get non of the dependencies we use, such as `conf_d`.
